version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    volumes:
      - ./back-end:/app
    networks:
      - softy-pinko-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./front-end:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - softy-pinko-network

networks:
  softy-pinko-network:
    driver: bridge