version: '3.8'

services:
  back-end:
    build: ./back-end
    networks:
      - softy-pinko-network

  front-end:
    build: ./front-end
    networks:
      - softy-pinko-network

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    networks:
      - softy-pinko-network

networks:
  softy-pinko-network:
    driver: bridge